-- QUICK FIX: Add missing columns immediately
-- Run this in Supabase Dashboard SQL Editor

-- Fix journal_entries table
ALTER TABLE journal_entries 
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'personal',
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS word_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS reading_time INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'english',
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS template_used TEXT,
ADD COLUMN IF NOT EXISTS entry_date DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS verse_reference TEXT,
ADD COLUMN IF NOT EXISTS verse_text TEXT,
ADD COLUMN IF NOT EXISTS verse_references TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS mood TEXT,
ADD COLUMN IF NOT EXISTS spiritual_state TEXT;

-- Fix sermons table  
ALTER TABLE sermons
ADD COLUMN IF NOT EXISTS scripture_reference TEXT,
ADD COLUMN IF NOT EXISTS main_points TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS congregation TEXT,
ADD COLUMN IF NOT EXISTS sermon_date DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS duration INTEGER,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS private_notes TEXT,
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS word_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_time INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_duration INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'english',
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'general',
ADD COLUMN IF NOT EXISTS illustrations TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS applications TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS series_name TEXT,
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS template_type TEXT;

-- Fix content column constraints
ALTER TABLE sermons ALTER COLUMN content DROP NOT NULL;
ALTER TABLE sermons ALTER COLUMN content SET DEFAULT '';
ALTER TABLE sermons ALTER COLUMN title DROP NOT NULL; 