// Export Utilities for Research Lab Agent Outputs
// Supports PDF, Markdown, and DOCX export formats

import jsPDF from 'jspdf';

export interface ExportOptions {
  format: 'pdf' | 'markdown' | 'txt' | 'json';
  filename?: string;
  includeMetadata?: boolean;
  includeSources?: boolean;
}

export interface ExportableContent {
  title?: string;
  content: string | any;
  metadata?: {
    agentType?: string;
    generatedAt?: string;
    sourcesUsed?: Array<{ id: string; title: string }>;
    [key: string]: any;
  };
}

/**
 * Export content as PDF
 */
export async function exportAsPDF(
  data: ExportableContent,
  options: ExportOptions = { format: 'pdf' }
): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper to add text with word wrapping
  const addText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    
    const lines = doc.splitTextToSize(text, maxWidth);
    
    if (yPosition + (lines.length * fontSize * 0.4) > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    
    lines.forEach((line: string) => {
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.4;
    });
    
    yPosition += 5; // Add spacing after text block
  };

  // Title
  if (data.title) {
    addText(data.title, 18, true);
    yPosition += 5;
  }

  // Metadata
  if (options.includeMetadata && data.metadata) {
    addText('Metadata', 14, true);
    if (data.metadata.agentType) {
      addText(`Agent Type: ${data.metadata.agentType}`, 10);
    }
    if (data.metadata.generatedAt) {
      addText(`Generated: ${new Date(data.metadata.generatedAt).toLocaleString()}`, 10);
    }
    yPosition += 5;
  }

  // Content
  const contentText = typeof data.content === 'string' 
    ? data.content 
    : JSON.stringify(data.content, null, 2);
  
  addText('Content', 14, true);
  addText(contentText, 11);

  // Sources
  if (options.includeSources && data.metadata?.sourcesUsed) {
    yPosition += 10;
    addText('Sources Used', 14, true);
    data.metadata.sourcesUsed.forEach((source) => {
      addText(`- ${source.title}`, 10);
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Bible Aura Research Lab`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save
  const filename = options.filename || `${data.title || 'export'}.pdf`;
  doc.save(filename);
}

/**
 * Export content as Markdown
 */
export function exportAsMarkdown(
  data: ExportableContent,
  options: ExportOptions = { format: 'markdown' }
): void {
  let markdown = '';

  // Title
  if (data.title) {
    markdown += `# ${data.title}\n\n`;
  }

  // Metadata
  if (options.includeMetadata && data.metadata) {
    markdown += '## Metadata\n\n';
    if (data.metadata.agentType) {
      markdown += `- **Agent Type:** ${data.metadata.agentType}\n`;
    }
    if (data.metadata.generatedAt) {
      markdown += `- **Generated:** ${new Date(data.metadata.generatedAt).toLocaleString()}\n`;
    }
    markdown += '\n';
  }

  // Content
  markdown += '## Content\n\n';
  const contentText = typeof data.content === 'string' 
    ? data.content 
    : '```json\n' + JSON.stringify(data.content, null, 2) + '\n```';
  markdown += contentText + '\n\n';

  // Sources
  if (options.includeSources && data.metadata?.sourcesUsed) {
    markdown += '## Sources Used\n\n';
    data.metadata.sourcesUsed.forEach((source) => {
      markdown += `- ${source.title}\n`;
    });
    markdown += '\n';
  }

  // Footer
  markdown += '---\n\n';
  markdown += `*Generated by Bible Aura Research Lab*\n`;

  // Download
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = options.filename || `${data.title || 'export'}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export content as plain text
 */
export function exportAsText(
  data: ExportableContent,
  options: ExportOptions = { format: 'txt' }
): void {
  let text = '';

  // Title
  if (data.title) {
    text += `${data.title}\n${'='.repeat(data.title.length)}\n\n`;
  }

  // Metadata
  if (options.includeMetadata && data.metadata) {
    text += 'METADATA\n';
    text += '-'.repeat(20) + '\n';
    if (data.metadata.agentType) {
      text += `Agent Type: ${data.metadata.agentType}\n`;
    }
    if (data.metadata.generatedAt) {
      text += `Generated: ${new Date(data.metadata.generatedAt).toLocaleString()}\n`;
    }
    text += '\n';
  }

  // Content
  text += 'CONTENT\n';
  text += '-'.repeat(20) + '\n';
  const contentText = typeof data.content === 'string' 
    ? data.content 
    : JSON.stringify(data.content, null, 2);
  text += contentText + '\n\n';

  // Sources
  if (options.includeSources && data.metadata?.sourcesUsed) {
    text += 'SOURCES USED\n';
    text += '-'.repeat(20) + '\n';
    data.metadata.sourcesUsed.forEach((source) => {
      text += `- ${source.title}\n`;
    });
    text += '\n';
  }

  // Footer
  text += '\n' + '-'.repeat(50) + '\n';
  text += 'Generated by Bible Aura Research Lab\n';

  // Download
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = options.filename || `${data.title || 'export'}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export content as JSON
 */
export function exportAsJSON(
  data: ExportableContent,
  options: ExportOptions = { format: 'json' }
): void {
  const jsonData = {
    title: data.title,
    content: data.content,
    metadata: data.metadata,
    exportedAt: new Date().toISOString(),
    exportedBy: 'Bible Aura Research Lab',
  };

  const jsonString = JSON.stringify(jsonData, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = options.filename || `${data.title || 'export'}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Main export function that routes to appropriate format
 */
export async function exportContent(
  data: ExportableContent,
  options: ExportOptions
): Promise<void> {
  switch (options.format) {
    case 'pdf':
      await exportAsPDF(data, options);
      break;
    case 'markdown':
      exportAsMarkdown(data, options);
      break;
    case 'txt':
      exportAsText(data, options);
      break;
    case 'json':
      exportAsJSON(data, options);
      break;
    default:
      throw new Error(`Unsupported export format: ${options.format}`);
  }
}

/**
 * Format agent output for export
 */
export function formatAgentOutputForExport(output: any): ExportableContent {
  const agentTypeMap: Record<string, string> = {
    'summarization': 'Summary',
    'theology_qa': 'Q&A Response',
    'cross_references': 'Cross-References',
    'curriculum': 'Bible Study Curriculum',
    'sermon': 'Sermon Outline',
    'doctrinal_harmony': 'Doctrinal Analysis',
    'translation': 'Translation',
  };

  const title = agentTypeMap[output.output_type] || 'Agent Output';
  
  // Extract content based on output type
  let content: string | any;
  if (typeof output.content === 'string') {
    content = output.content;
  } else if (output.content && typeof output.content === 'object') {
    // Handle structured content
    if (output.content.summary) {
      content = output.content.summary;
    } else if (output.content.answer) {
      content = output.content.answer;
    } else if (output.content.crossReferences) {
      content = output.content.crossReferences;
    } else if (output.content.curriculum) {
      content = output.content.curriculum;
    } else if (output.content.sermon) {
      content = output.content.sermon;
    } else if (output.content.harmonization) {
      content = output.content.harmonization;
    } else if (output.content.translation) {
      content = `Original (${output.content.targetLanguage || 'en'}):\n${output.content.originalText || ''}\n\nTranslation:\n${output.content.translation}`;
    } else {
      content = JSON.stringify(output.content, null, 2);
    }
  } else {
    content = 'No content available';
  }

  return {
    title: output.content?.topic || output.content?.question || output.content?.verseReference || output.content?.originalText?.substring(0, 50) || title,
    content,
    metadata: {
      agentType: output.output_type,
      generatedAt: output.generated_at || output.created_at,
      sourcesUsed: output.content?.sourcesUsed || output.content?.sourceIds?.map((id: string) => ({ id, title: 'Source' })) || [],
      ...output.metadata,
    },
  };
}

